# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:53
from __future__ import unicode_literals

from django.db import models, migrations

def load_modes(apps, schema_editor):
    mode = apps.get_model("chaos", "Mode")
    m = mode(id=0, mode='normal', is_active=True)
    m.save()
    m = mode(id=1, mode='degraded', is_active=False)
    m.save()
    m = mode(id=2, mode='failure', is_active=False)
    m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_modes),
    ]