# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaos',
            name='is_active',
        ),
    ]
