# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0002_remove_chaos_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaos',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
